---
title: "Client Report - Project 0: Introduction"
subtitle: "Course DS 250"
author: "Sean Porter"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

## Elevator pitch

This was done as an introductory project to get familiar with the tools we will be using in this class. I installed all necessary libraries and ensured that I could display everything properly within an HTML document.

## Readings

Finish the readings and be prepared with any questions to get your environment working smoothly.

I was able to read through the material and get the environment working on my device. I worked with the tutoring lab to fix any errors.


## Example Chart

In VS Code, write a python script to create the example chart from section 3.2.2 of the textbook (part of the assigned readings). Note that you will be using Plotly Express to display the chart instead of Altair which is used in the book.

I was able to write a python script to create the example chart from section 3.2.2 of the textbook.

I used the resources from "Learn About Plotly Express" to create this chart.

```{python}
#| label: Q2 chart

import plotly.express as px
import pandas as pd

url = "https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/mpg/mpg.csv"
mpg = pd.read_csv(url)
mpg.head()

fig = px.scatter(mpg, x="displ", y="hwy", title="Example Scatter Plot") #Create a scatter plot with labels and a title
fig.show() #Show the scatter plot
```

## Included Markdown Table

Your final report should also include the markdown table created from the following (assuming you have mpg from question 2).

I was able to create a markdown table in HTML format from the following and submit it on canvas.
